name: "Test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow running on any branch through button-click
  workflow_dispatch:

jobs:
  test:
    name: Full testing process
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      pull-requests: write
      statuses: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'typescript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: NPM caching
      uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # v3.2.0
      with:
        node-version: '16'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'

    - name: Install dependencies
      run: yarn install
      working-directory: Meadowlark-js

    - name: Linter
      run: yarn test:lint
      working-directory: Meadowlark-js

    - name: Unit tests with code coverage
      run: yarn test:unit:coverage --ci
      working-directory: Meadowlark-js

    - name: Archive coverage results
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
      with:
        name: code-coverage-report
        path: Meadowlark-js/coverage/lcov-report

    # This needs to upload test results with the dorny-reporter, coming soon.
